### PR TITLE
GroupID

### PR DESCRIPTION
**Pull request by StabbyCutyou**
ping @jandre 

So if we go with group id (which I'm largely in favor of cus it simplifies a lot of things), we need to update the SDK unfortunately. We make use of this type in the main repo as well.

### CODE REVIEW

**Comment by jandre** [comment]
Question:  do we need to? if it's not in the json coming up from the trigger container, won't it just popualte to empty string when it unmarshals to models.TriggerEvent?  trigger containers should never be retrying

**Comment by jandre** [comment]
anyway i believe you, f it just merge it - please tag a new 0.2.x version

**Comment by StabbyCutyou** [comment]
I'm double checking now... it's all very confusing because I think this is one of those places where we use different structs with the same definitions to do json parsing because of ???

So, I think we need this, but making absolutely sure.

**Comment by StabbyCutyou** [comment]
Yea... sigh

So "TriggerEvent" lives both in models/trigger and here.

We use them in different places for what surmounts to the same purpose. I could refactor the komand / engine code to use the one in models only, but i imagine the initial idea was we should always be trusting the SDKs message format.

This isn't an issue for the other SDKs as we'll never publish a retry job via SDK, and only an issue for this one because the TriggerEvent struct is load bearing inside of the core product :/

**Comment by jandre** [comment]
Yeah.. ideally we would put things that the backend woudl set like
'ID/GroupID' etc in the 'Meta' field of the event, which was designed to be
a generic json 'passed through' by the trigger/action plugins so we
wouldn''t have to change the event structure for the plugins sdks.    but i
don't think it's a big deal

**Pull request merged**
